language: csharp
solution: Lidgren.Network.sln
install:
  - nuget restore Lidgren.Network.sln
script:
  - msbuild /p:Configuration=Release Lidgren.Network.sln
  - mono ./UnitTests/bin/Release/UnitTests.exe
